name: gs_lightning
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11.11
  - pip=24.3.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - imageio
    - ninja
    - numpy<2
    - opencv-python
    - plyfile
    - pillow==9.4.0
    - pycolmap
    - torchaudio==2.0.2
    - torchvision==0.15.2
